name: 'Update schedule'

on:
  schedule:
    - cron: '0 22 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    branches:
      - master
      - dev
      - gd
jobs:
  push:
    runs-on: ${{ matrix.operating-system }}
    timeout-minutes: 120
    strategy:
      matrix:
        operating-system: ['ubuntu-22.04']
    steps:
    - name: Set up WARP with client
      uses: fscarmen/warp-on-actions@v1.3
      with:
        stack: dual
        mode: client
